main:
  - title: 项目
    link: /projects
    icon: ri:box-3-line
    view: elastic
  - title: 友邻
    link: /links
    icon: ri:heart-line
    view: elastic
  - title: 自述
    link: /about
    icon: ri:user-line
    view: elastic
  - title: 归档
    link: /archives
    icon: ri:archive-line
    view: elastic-icon
  - title: 留言
    link: /message-board
    icon: ri:message-3-line
    view: elastic-icon
