name: Next Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Depker
        run: |
          wget -O /usr/local/bin/depker https://github.com/syfxlin/depker/releases/latest/download/depker.linux.amd64
          chmod +x /usr/local/bin/depker
      - name: Deploy to docker
        run: |
          depker --version
          depker deploy
        env:
          TZ: Asia/Shanghai
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_CA: ${{ secrets.REMOTE_CA }}
          REMOTE_CERT: ${{ secrets.REMOTE_CERT }}
          REMOTE_KEY: ${{ secrets.REMOTE_KEY }}
